### ISSUE TITLE
目录超链接位置不准确

### ISSUE THREAD

**Issue by superbillgates** [dustincys/PlutoThesis#1]
点击目录超链接，会定位到标题之下的正文，而非标题本身。
请您帮忙修正，十分感谢！

**Comment by dustincys** [comment]
hi, superbillgates, 其实这个不算bug, 因为图书馆最后不太关心这个链接准不准确，但我尽快改正

**Comment by superbillgates** [comment]
看了下引用的是hyperref包，应该会直接定位到标题，但想不明白为啥会有这个问题，有点儿强迫症哈~~~十分感谢啦！
