### ISSUE TITLE
附录的标题和公式编号问题

### ISSUE THREAD

**Issue by ivanshih** [dustincys/PlutoThesis#2]
附录部分好像有点问题，附录的标题只有 附录 两个字，没有加A或B等，而且公式的编号也不是（A-1）或（B-1）。

解决办法：
\renewcommand{\appendixname}{附录~\Alph{chapter}}

\renewcommand{\theequation}{\Alph{chapter}-\arabic{equation}}

\renewcommand{\thetable}{\Alph{chapter}-\arabic{table}}

**Comment by dustincys** [comment]
@ivanshih  谢谢！　已更新
